### ISSUE TITLE
[Task] Add Hungary in bi-weekly deliverables

### ISSUE THREAD

**Issue by 510stefania** [rodekruis/social-media-listening#36]
**Who is your contact person for this task?**
DS: Jacopo
HCD: Stefania
TPC: Lars

**Overview**

- On 09/09/23 Hungary requested and gave green light to get SML service
- On 21/08/23 Hungary NS provided Telegram groups and team details

**Objective**

- Implement deliverable to current scrape 17 -> first delivery 30/08/23

```[tasklist]
### Tasks
- [ ] https://github.com/rodekruis/social-media-listening/issues/37
- [ ] https://github.com/rodekruis/social-media-listening/issues/38
- [ ] https://github.com/rodekruis/social-media-listening/issues/39
```
